In [11]:
import pandas as pd
tickers_list = ['AAPL', 'WMT', 'IBM', 'MU', 'BA', 'AXP','DIS', 'TSLA', 'AMZN', 'GOOGL']

# Fetch the data
import yfinance as yf
data = yf.download(tickers_list,'2015-1-1')['Adj Close']

[*********************100%***********************]  10 of 10 completed


In [12]:
print(data)

                  AAPL        AMZN         AXP          BA        DIS  \
Date                                                                    
2015-01-02   24.531765   15.426000   81.618019  113.657227  87.376259   
2015-01-05   23.840668   15.109500   79.459549  112.870071  86.099403   
2015-01-06   23.842909   14.764500   77.766106  111.540627  85.642715   
2015-01-07   24.177237   14.921000   79.464531  113.272392  86.518814   
2015-01-08   25.106184   15.023000   80.590919  115.275276  87.413544   
...                ...         ...         ...         ...        ...   
2023-07-12  189.770004  130.800003  174.330002  217.110001  90.150002   
2023-07-13  190.539993  134.300003  174.240005  216.850006  90.470001   
2023-07-14  190.690002  134.679993  173.389999  213.119995  88.620003   
2023-07-17  193.990005  133.559998  175.389999  211.869995  85.559998   
2023-07-18  193.770004         NaN  177.960007  210.104996  86.279198   

                 GOOGL         IBM         MU     

In [13]:
data.dropna()

AAPL        AMZN         AXP          BA        DIS  \
Date                                                                    
2015-01-02   24.531765   15.426000   81.618019  113.657227  87.376259   
2015-01-05   23.840668   15.109500   79.459549  112.870071  86.099403   
2015-01-06   23.842909   14.764500   77.766106  111.540627  85.642715   
2015-01-07   24.177237   14.921000   79.464531  113.272392  86.518814   
2015-01-08   25.106184   15.023000   80.590919  115.275276  87.413544   
...                ...         ...         ...         ...        ...   
2023-07-11  188.080002  128.779999  174.639999  218.759995  89.489998   
2023-07-12  189.770004  130.800003  174.330002  217.110001  90.150002   
2023-07-13  190.539993  134.300003  174.240005  216.850006  90.470001   
2023-07-14  190.690002  134.679993  173.389999  213.119995  88.620003   
2023-07-17  193.990005  133.559998  175.389999  211.869995  85.559998   

                 GOOGL         IBM         MU        TSLA         WMT  
Date                                                                   
2015-01-02   26.477501  106.693794  34.264706   14.620667   71.685669  
2015-01-05   25.973000  105.014954  33.308254   14.006000   71.477036  
2015-01-06   25.332001  102.750221  32.410961   14.085333   72.027817  
2015-01-07   25.257500  102.078667  31.651714   14.063333   73.938873  
2015-01-08   25.345501  104.297348  33.199795   14.041333   75.499420  
...                ...         ...        ...         ...         ...  
2023-07-11  117.139999  134.440002  63.599998  269.790009  154.649994  
2023-07-12  118.930000  132.839996  63.790001  271.989990  155.039993  
2023-07-13  124.540001  133.919998  64.529999  277.899994  154.130005  
2023-07-14  125.419998  133.399994  64.080002  281.380005  154.660004  
2023-07-17  124.650002  134.240005  65.160004  290.380005  154.850006  

[2148 rows x 10 columns]

In [14]:
import numpy as np
import pandas as pd
import tensorflow as tf
from sklearn.metrics import accuracy_score, precision_score, recall_score
from sklearn.model_selection import train_test_split

In [15]:

# Define the parsimonious neural network model
def build_model(input_dim, output_dim):
    # input_dim = data.shape[0]
    # output_dim = data.shape[1]
    model = tf.keras.Sequential([
        tf.keras.layers.Dense(32, activation='relu', input_shape=(input_dim,)),
        tf.keras.layers.Dense(output_dim, activation='softmax')
    ])
    return model

In [16]:
# Define the portfolio optimization problem
def portfolio_optimization(inputs):
    # Define your objective function and constraints
    # You can use any suitable optimization formulation
    
    # For example, minimize the risk (variance) subject to a target return
    expected_returns = np.mean(inputs, axis=0)
    cov_matrix = np.cov(inputs, rowvar=False)
    target_return = 0.1
    
    num_assets = inputs.shape[1]
    
    # Define objective function
    def objective(weights):
        variance = np.dot(np.dot(weights, cov_matrix), weights.T)
        return variance
    
    # Define constraint function for target return
    def constraint(weights):
        return np.dot(weights, expected_returns) - target_return
    
    return objective, constraint, num_assets

# # Load historical stock data separately for each stock
# stock_data = {}

# # Replace the placeholders with the actual filenames for each stock
# stock_data['AAPL'] = pd.read_csv('AAPL.csv')
# stock_data['GOOGL'] = pd.read_csv('GOOGL.csv')
# stock_data['MSFT'] = pd.read_csv('MSFT.csv')
# stock_data['AMZN'] = pd.read_csv('AMZN.csv')
# stock_data['FB'] = pd.read_csv('FB.csv')
# stock_data['JPM'] = pd.read_csv('JPM.csv')
# stock_data['WMT'] = pd.read_csv('WMT.csv')
# stock_data['TSLA'] = pd.read_csv('TSLA.csv')
# stock_data['BRK.A'] = pd.read_csv('BRK.A.csv')
# stock_data['V'] = pd.read_csv('V.csv')

# # Merge stock data into a single dataframe
# merged_data = pd.DataFrame()
# for symbol in stock_data:
#     stock_returns = (stock_data[symbol]['Close'] - stock_data[symbol]['Close'].shift(1)) / stock_data[symbol]['Close'].shift(1)
#     merged_data[symbol] = stock_returns

# merged_data = merged_data.dropna()  # Drop rows with missing values


In [17]:
# Define the portfolio optimization problem
objective_fn, constraint_fn, num_assets = portfolio_optimization(data.values)

In [18]:
# Prepare the data for training and testing the model
X = data.values
y = np.zeros((data.shape[0], num_assets))
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)


In [19]:
# Build the neural network model
model = build_model(num_assets, num_assets)

In [20]:
# Compile the model
model.compile(optimizer='adam', loss='categorical_crossentropy')

In [21]:
# Train the model
model.fit(X_train, y_train, epochs=100, verbose=0)

In [34]:
print(X_train)

[[110.28791809 153.90499878 101.90327454 ...  49.50880051 147.25332642
  130.53741455]
 [ 50.82343292  88.8144989  113.74967194 ...  44.63779831  15.04066658
  107.57512665]
 [ 45.05770111  80.14550018  94.13908386 ...  51.09632492  20.07066727
   76.4252243 ]
 ...
 [ 48.88708878  96.10949707 117.68140411 ...  39.54985428  15.14466667
  103.63793182]
 [ 70.51846313  98.63700104 115.08499908 ...  51.37240982  53.32733154
  108.18058777]
 [ 45.83179855  83.2634964   92.31052399 ...  58.27464676  19.78266716
   78.29508972]]


In [35]:
print(X_test)

[[ 48.81231689  89.2460022  117.13276672 ...  41.54165268  15.26733303
   99.06401062]
 [177.63674927 169.31500244 186.97930908 ...  81.10363007 366.52334595
  144.36968994]
 [ 44.71667099  75.61450195 101.20344543 ...  36.3156662   23.56466675
   89.22275543]
 ...
 [ 37.99281311  49.12900162  79.44801331 ...  33.81113434  24.18333244
   71.70522308]
 [137.70985413 112.90000153 134.78622437 ...  52.42543793 217.24000549
  129.65144348]
 [133.33831787 163.10650635 124.32402802 ...  85.27228546 270.55334473
  138.47584534]]


In [36]:
print(y_train)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [32]:
# Extract the weights from the trained model
weights = model.get_weights() #[0]

In [23]:
# Normalize the weights to get portfolio allocations
portfolio_allocations = weights / np.sum(weights, axis=1, keepdims=True)

In [33]:
print(weights)

[array([[nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
        nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
        nan, nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
        nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
        nan, nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
        nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
        nan, nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
        nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
        nan, nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
        nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
        nan, nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
 

In [24]:
# Rebalance the portfolio based on the calculated allocations
portfolio_value = 1000000  # Initial portfolio value
investment_amounts = portfolio_value * portfolio_allocations[-1]  # Use the latest allocation


In [41]:
print(portfolio_allocations[-1].shape)

10

In [25]:
# Generate buy/sell/retain/ignore signals based on the rebalanced portfolio
stock_signals = {}
for symbol, allocation in zip(data.columns, portfolio_allocations[-1]):
    if allocation.argmax() == 0:
        stock_signals[symbol] = "Buy"
    elif allocation.argmax() == 1:
        stock_signals[symbol] = "Sell"
    elif allocation.argmax() == 2:
        stock_signals[symbol] = "Retain"
    else:
        stock_signals[symbol] = "Ignore"

In [ ]:
# Calculate model performance metrics on the test set
y_pred = model.predict(X_test)
y_pred_labels = np.argmax(y_pred, axis=1)
y_test_labels = np.argmax(y_test, axis=1)

accuracy = accuracy_score(y_test_labels, y_pred_labels)
precision = precision_score(y_test_labels, y_pred_labels, average='macro')
recall = recall_score(y_test_labels, y_pred_labels, average='macro')
loss = model.evaluate(X_test, y_test, verbose=0)

# print("Investment amounts after rebalancing:")
# print(investment_amounts)

In [27]:
print("Stock signals:")
print(stock_signals)

Stock signals:
{'AAPL': 'Buy', 'AMZN': 'Buy', 'AXP': 'Buy', 'BA': 'Buy', 'DIS': 'Buy', 'GOOGL': 'Buy', 'IBM': 'Buy', 'MU': 'Buy', 'TSLA': 'Buy', 'WMT': 'Buy'}


In [37]:
print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("Loss:", loss)

Accuracy: 1.0
Precision: 1.0
Recall: 1.0
Loss: nan
